// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: service_destination.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DestinationServiceClient is the client API for DestinationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DestinationServiceClient interface {
	ProccessMessage(ctx context.Context, in *ProccessMessageRequest, opts ...grpc.CallOption) (*ProccessMessageResponse, error)
}

type destinationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDestinationServiceClient(cc grpc.ClientConnInterface) DestinationServiceClient {
	return &destinationServiceClient{cc}
}

func (c *destinationServiceClient) ProccessMessage(ctx context.Context, in *ProccessMessageRequest, opts ...grpc.CallOption) (*ProccessMessageResponse, error) {
	out := new(ProccessMessageResponse)
	err := c.cc.Invoke(ctx, "/pb.DestinationService/ProccessMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DestinationServiceServer is the server API for DestinationService service.
// All implementations must embed UnimplementedDestinationServiceServer
// for forward compatibility
type DestinationServiceServer interface {
	ProccessMessage(context.Context, *ProccessMessageRequest) (*ProccessMessageResponse, error)
	mustEmbedUnimplementedDestinationServiceServer()
}

// UnimplementedDestinationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDestinationServiceServer struct {
}

func (UnimplementedDestinationServiceServer) ProccessMessage(context.Context, *ProccessMessageRequest) (*ProccessMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProccessMessage not implemented")
}
func (UnimplementedDestinationServiceServer) mustEmbedUnimplementedDestinationServiceServer() {}

// UnsafeDestinationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DestinationServiceServer will
// result in compilation errors.
type UnsafeDestinationServiceServer interface {
	mustEmbedUnimplementedDestinationServiceServer()
}

func RegisterDestinationServiceServer(s grpc.ServiceRegistrar, srv DestinationServiceServer) {
	s.RegisterService(&DestinationService_ServiceDesc, srv)
}

func _DestinationService_ProccessMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProccessMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DestinationServiceServer).ProccessMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DestinationService/ProccessMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DestinationServiceServer).ProccessMessage(ctx, req.(*ProccessMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DestinationService_ServiceDesc is the grpc.ServiceDesc for DestinationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DestinationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.DestinationService",
	HandlerType: (*DestinationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProccessMessage",
			Handler:    _DestinationService_ProccessMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_destination.proto",
}
